name: Pull Request

on:
  pull_request:
    branches: ['master']

jobs:
  codestyle:
    runs-on: ubuntu-latest

    name: Codestyle

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Check prettier
        run: npx prettier --check .

      - name: Check eslint
        run: npx eslint --max-warnings 0 .
